name: teacher
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # App Core
  core:
    path: ../core

  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  country_flags: ^2.2.0
  flutter_svg: ^2.0.10+1
  bottom_sheet: ^4.0.2
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  timeline_tile: ^2.0.0
  aad_oauth: ^1.0.1
  flutter_dotenv: ^5.1.0
  pull_to_refresh_flutter3: ^2.0.2
  qr_code_scanner: ^1.0.1
  expandable: ^5.0.1
  # intl: 0.18.1
  weekly_date_picker: ^1.4.2
  getwidget: ^4.0.0
  custom_refresh_indicator: ^3.1.0
  flutter_hooks: ^0.20.5

  # Copy from IPortal2
  network_data_source:
    path: packages/network_data_source
  repository:
    path: packages/repository
  local_data_source:
    path: packages/local_data_source
  meta: ^1.10.0
  bloc: ^8.1.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.3.7
  get_it: ^7.6.7
  injectable: ^2.3.2
  pin_code_fields: ^8.0.1
  otp_text_field: ^1.1.3
  draggable_scrollbar: ^0.1.0
  carousel_slider: ^4.2.1
  flutter_custom_tabs: ^2.0.0+1
  page_transition: ^2.1.0
  tab_container: ^2.0.0
  file_picker: ^8.0.0+1
  share_plus: ^7.0.2
  http: ^1.2.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_gen_runner:

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/main_background/
    - assets/icons/brand_background/
    - assets/images/brand_logo/
    - assets/images/logo_app/
    - assets/icons/
    - assets/icons/features/
    - assets/images/login/
    - assets/images/splash/
    - .env
