include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - avoid_redundant_argument_values: false
    - avoid_print: false
    - prefer_single_quotes: true 
    - unused_local_variable: false
