environment_config:
  path: app_config/env_config.dart
  class: EnvironmentConfig

  fields:
    env:
    baseUrl:
  extensions:
    dev:
      fields:
        env:
          env_var: APP_ENV
          default: 'dev'
          dotenv: true
        baseUrl:
          env_var: BASE_URL
          const: false
          default: ''
    uat:
      fields:
        env:
          env_var: APP_ENV
          default: 'staging'
          dotenv: true
        baseUrl:
          env_var: BASE_URL
          const: false
          default: ''
    staging:
      fields:
        env:
          env_var: APP_ENV
          default: 'staging'
          dotenv: true
        baseUrl:
          env_var: BASE_URL
          const: false
          default: ''
    prod:
      fields:
        env:
          env_var: APP_ENV
          default: 'prod'
          dotenv: true
        baseUrl:
          env_var: BASE_URL
          const: false
          default: ''
