#! /bin/bash

function run_pub_gen() {
	flutter pub get
	dart run build_runner build -d
}

function clean() {
	run_clean_packages
	run_clean
}

function run_clean() {
	echo "================== Clean =================="
	flutter clean
	flutter pub get
	cd ios
	rm -rf Pods
	rm -rf Podfile.lock
	pod install --repo-update
	cd ..
	dart run build_runner build -d
}

function run_clean_packages() {
	cd packages
	for d in */ ; do
		cd $d
		flutter clean
		flutter pub get
		dart run build_runner build -d
		cd ..
	done
}

function main() {
	echo "Choose function to run:"
	select app in "run_pub_gen" "clean"; do
		case $app in
			run_pub_gen)
				run_pub_gen
				break
				;;
			clean)
				clean
				break
				;;
			*)
				echo "Invalid choice."
				;;
		esac
	done
}

# if no arguments are passed, run the main function
if [ $# -eq 0 ]; then
	main
else
	$@
fi
