class PhoneBook {
  final String name;
  final String id;
  final String image;
  final String numberPhone;
  final String subject;
  final String email;
  final String lop;
  final String nameParent;
  final String phoneParent;
  PhoneBook(
      {required this.id,
      required this.email,
      required this.nameParent,
      required this.image,
      required this.name,
      required this.lop,
      required this.phoneParent,
      required this.numberPhone,
      required this.subject});
}

final List<PhoneBook> phoneBook = [
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      numberPhone: '0914316170',
      subject: 'Toán',
      id: 'MHS1123456',
      image: 'assets/images/image-phone-book.png',
      name: 'Hà Anh Minh'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      numberPhone: '0914316170',
      subject: 'Toán',
      id: 'MHS1123456',
      image: 'assets/images/image-phone-book.png',
      name: 'Hạ Trang'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-phone-book.png',
      name: 'Đinh Thuỳ Linh'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-phone-book.png',
      name: 'Nghiêm Ngọc Trân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-phone-book.png',
      name: 'Hà Nguyễn'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-phone-book.png',
      name: 'Hoàng Anh'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      subject: 'Toán',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      image: 'assets/images/image-phone-book.png',
      name: 'Thị Nhi'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-phone-book.png',
      name: 'Đinh Quốc thái'),
];

final List<PhoneBook> phoneBookTeacher = [
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      image: 'assets/images/image-teacher.png',
      subject: 'Toán',
      name: 'Hà Anh Minh'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-teacher.png',
      name: 'Hạ Trang'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-teacher.png',
      name: 'Nguyễn Trung Quân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-teacher.png',
      name: 'Đinh Thuỳ Linh'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-teacher.png',
      name: 'Nghiêm Ngọc Trân'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      numberPhone: '0914316170',
      subject: 'Toán',
      image: 'assets/images/image-teacher.png',
      name: 'Hà Nguyễn'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-teacher.png',
      name: 'Hoàng Anh'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-teacher.png',
      name: 'Thị Nhi'),
  PhoneBook(
      phoneParent: '09992383783',
      lop: '6.1',
      nameParent: 'Ho Thu Thuy',
      email: 'NHG@.com',
      id: 'MHS1123456',
      subject: 'Toán',
      numberPhone: '0914316170',
      image: 'assets/images/image-teacher.png',
      name: 'Đinh Quốc thái'),
];
