class GalleryModel {
  final int id;
  final String qty;
  final String name;
  final String description;
  final bool isPinned;
  final String imgUrl;
  final List<String> imgUrlList;

  GalleryModel({
    required this.id,
    required this.qty,
    required this.name,
    required this.description,
    required this.isPinned,
    required this.imgUrl,
    required this.imgUrlList,
  });
}

final List<GalleryModel> galleryList = [
  GalleryModel(
    id: 1,
    qty: '15',
    name: 'Hội khoẻ Phù Đổng Thiên Vương',
    description:
        'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ. Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
    isPinned: true,
    imgUrl: "assets/images/gallery-1.png",
    imgUrlList: [
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-4.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-6.png",
      "assets/images/gallery-7.png",
      "assets/images/gallery-8.png",
      "assets/images/gallery-9.png",
      "assets/images/gallery-10.png",
      "assets/images/gallery-11.png",
      "assets/images/gallery-12.png",
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-7.png",
    ],
  ),
  GalleryModel(
    id: 2,
    qty: '5',
    name: 'Đêm hội trăng rằm',
    description:
        'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ. Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
    isPinned: true,
    imgUrl: "assets/images/gallery-2.png",
    imgUrlList: [
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-4.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-6.png",
      "assets/images/gallery-7.png",
      "assets/images/gallery-8.png",
      "assets/images/gallery-9.png",
      "assets/images/gallery-10.png",
      "assets/images/gallery-11.png",
      "assets/images/gallery-12.png",
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-7.png",
    ],
  ),
  GalleryModel(
    id: 3,
    qty: '15',
    name: 'Cuộc thi vẽ',
    description:
        'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
    isPinned: true,
    imgUrl: "assets/images/gallery-3.png",
    imgUrlList: [
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-4.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-6.png",
      "assets/images/gallery-7.png",
      "assets/images/gallery-8.png",
      "assets/images/gallery-9.png",
      "assets/images/gallery-10.png",
      "assets/images/gallery-11.png",
      "assets/images/gallery-12.png",
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-7.png",
    ],
  ),
  GalleryModel(
    id: 4,
    qty: '23',
    name: 'Lớp học nấu ăn',
    description:
        'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
    isPinned: false,
    imgUrl: "assets/images/gallery-4.png",
    imgUrlList: [
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-4.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-6.png",
      "assets/images/gallery-7.png",
      "assets/images/gallery-8.png",
      "assets/images/gallery-9.png",
      "assets/images/gallery-10.png",
      "assets/images/gallery-11.png",
      "assets/images/gallery-12.png",
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-7.png",
    ],
  ),
  GalleryModel(
    id: 5,
    qty: '15',
    name: 'Hội khoẻ Phù Đổng Thiên Vương',
    description:
        'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
    isPinned: false,
    imgUrl: "assets/images/gallery-5.png",
    imgUrlList: [
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-4.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-6.png",
      "assets/images/gallery-7.png",
      "assets/images/gallery-8.png",
      "assets/images/gallery-9.png",
      "assets/images/gallery-10.png",
      "assets/images/gallery-11.png",
      "assets/images/gallery-12.png",
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-7.png",
    ],
  ),
  GalleryModel(
    id: 6,
    qty: '22',
    name: 'Vở sạch chữ đẹp',
    description:
        'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
    isPinned: false,
    imgUrl: "assets/images/gallery-4.png",
    imgUrlList: [
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-4.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-6.png",
      "assets/images/gallery-7.png",
      "assets/images/gallery-8.png",
      "assets/images/gallery-9.png",
      "assets/images/gallery-10.png",
      "assets/images/gallery-11.png",
      "assets/images/gallery-12.png",
      "assets/images/gallery-1.png",
      "assets/images/gallery-2.png",
      "assets/images/gallery-3.png",
      "assets/images/gallery-5.png",
      "assets/images/gallery-7.png",
    ],
  ),
  GalleryModel(
      id: 7,
      qty: '15',
      name: 'Hội khoẻ Phù Đổng Thiên Vương',
      description:
          'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
      isPinned: false,
      imgUrl: "assets/images/gallery-5.png",
      imgUrlList: [
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
      ]),
  GalleryModel(
      id: 8,
      qty: '15',
      name: 'Hội khoẻ Phù Đổng Thiên Vương',
      description:
          'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
      isPinned: false,
      imgUrl: "assets/images/gallery-2.png",
      imgUrlList: [
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
      ]),
  GalleryModel(
      id: 9,
      qty: '15',
      name: 'Hội khoẻ Phù Đổng Thiên Vương',
      description:
          'Học sinh tham gia sôi nổi các cuộc thi vẽ tranh hàng năm là một hoạt động giáo dục và văn hóa đặc biệt được tổ chức định kỳ.',
      isPinned: false,
      imgUrl: "assets/images/gallery-3.png",
      imgUrlList: [
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
        "assets/images/gallery-1.png",
      ]),
];
