name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
# homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: ^5.4.3+1

  #base
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.0.7
  get_it: ^7.6.7
  injectable: ^2.0.0
  intl: ^0.19.0
  flutter_svg_provider: ^1.0.6
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.0.177

  freezed: ^2.5.1
  freezed_annotation: ^2.4.1

  #storage local
  flutter_secure_storage: ^9.0.0

  #localization - unused in current version
  # easy_localization: ^3.0.7

  #Firebase
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.1

  #utils
  logger: ^2.0.2+1 #ns
  pedantic: ^1.11.1 #ns
  date_format: ^2.0.2 #ns
  permission_handler: ^11.3.0 #ns
  extended_image: ^8.1.1 #ns
  image_editor: ^1.0.0 #ns
  uuid: ^4.3.3 #ns
  timeago: ^3.1.0 #ns
  mime: ^1.0.2 #ns
  webview_flutter: ^4.7.0
  sprintf: ^7.0.0

  tab_indicator_styler: ^2.0.0
  pin_code_fields: ^8.0.1

  #Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartx: ^1.1.0
  pull_to_refresh: ^2.0.0
  enum_to_string: ^2.0.1
  jwt_decode: ^0.3.1
  flutter_local_notifications: ^17.1.2
  keyboard_actions: ^4.0.0

  #JSON
  json_annotation: ^4.9.0
  universal_html: ^2.0.8
  country_code_picker: ^3.0.0
  phone_numbers_parser: ^8.1.3
  flutter_multi_formatter: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  adaptive_dialog: ^2.0.0
  expandable: ^5.0.1
  equatable: ^2.0.5

  #ui
  cached_network_image: ^3.3.0 #ns
  fluttertoast: ^8.0.8 #ns
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_spinkit: ^5.1.0 #ns
  flutter_easyloading: ^3.0.3 #ns
  modal_bottom_sheet: ^3.0.0-pre #ns
  dotted_border: ^2.0.0 #ns
  carousel_slider: ^4.1.1
  dots_indicator: ^3.0.0
  flutter_rating_bar: ^4.0.1
  device_info_plus: 9.0.2
  clipboard: ^0.1.3
  shake: ^2.2.0
  quiver: ^3.2.1
  google_fonts: ^6.2.1
  timeline_tile: ^2.0.0
  loader_overlay: ^4.0.0
  expansion_tile_group: ^1.2.4
  image_gallery_saver: ^2.0.3
  flutter_hooks: ^0.20.5
  image_picker: ^1.1.1
  aad_oauth: ^1.0.1
  firebase_crashlytics: ^3.5.5
  bloc: ^8.1.4
  skeletonizer: ^1.1.2+1
  flutter_inappwebview: ^6.0.0
  easy_image_viewer: ^1.5.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  hive_generator: ^2.0.0
  json_serializable: ^6.8.0
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/resources/

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
