import 'package:core/core.dart';

class PhoneBook {
  PhoneBook({
    required this.pupilId,
    required this.userId,
    required this.schoolId,
    required this.schoolName,
    required this.fullName,
    required this.userKey,
    required this.classId,
    required this.className,
    required this.email,
    required this.urlImage,
    required this.indentifier,
    required this.capDaoTao,
    required this.parentId,
    required this.parentName,
    required this.phoneNumber,
  });

  final int pupilId;
  final int userId;
  final int schoolId;
  final String schoolName;
  final String fullName;
  final String userKey;
  final int classId;
  final String className;
  final String email;
  final UrlImage urlImage;
  final String indentifier;
  final CapDaoTao capDaoTao;
  final int parentId;
  final String parentName;
  final String phoneNumber;

  factory PhoneBook.fromMap(Map<String, dynamic> map) {
    return PhoneBook(
      pupilId: map['pupil_id'],
      userId: map['user_id'],
      schoolId: map['school_id'],
      schoolName: map['school_name'],
      fullName: map['full_name'],
      userKey: map['user_key'],
      classId: map['class_id'],
      className: map['class_name'],
      email: map['email'],
      urlImage: UrlImage.fromMap(map['url_image']),
      indentifier: map['indentifier'],
      capDaoTao: CapDaoTao.fromMap(map['cap_dao_tao']),
      parentId: map['parent_id'],
      parentName: map['parent_name'],
      phoneNumber: map['phone_number'],
    );
  }
}

final List<PhoneBook> phoneBook = [
  PhoneBook(
    pupilId: 10056998,
    userId: 10126038,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Lê Thanh Phong",
    userKey: "0253240031",
    parentId: 10059823,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    phoneNumber: '0987 888 888',
    parentName: 'Nguyễn Kiều Cẩm Thơ',
  ),
  PhoneBook(
    pupilId: 10056997,
    userId: 10126036,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Xuân Phúc",
    userKey: "0253240030",
    parentId: 10059822,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    phoneNumber: '0987 888 888',
    parentName: 'Quế Ngọc Hải',
  ),
  PhoneBook(
    pupilId: 10056996,
    userId: 10126034,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Trần Bảo Anh",
    userKey: "0253240029",
    parentId: 10059821,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    phoneNumber: '0987 888 888',
    parentName: 'Trương Ánh Hoa',
  ),
  PhoneBook(
    pupilId: 10056979,
    userId: 10125980,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Vũ Lê Thiên Phúc",
    userKey: "0253240023",
    parentId: 10059804,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056978,
    userId: 10125978,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Bùi Tiến Minh",
    userKey: "0253240022",
    parentId: 10059803,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056977,
    userId: 10125976,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Hoàng Ánh Minh",
    userKey: "0253240021",
    parentId: 10059802,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056973,
    userId: 10125960,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Gia Phúc",
    userKey: "0253240019",
    parentId: 10059798,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056881,
    userId: 10125728,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Bùi Quốc",
    userKey: "0253240014",
    parentId: 10059703,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056880,
    userId: 10125725,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Trần Phương Anh",
    userKey: "0253240013",
    parentId: 10059702,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056879,
    userId: 10125723,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Bảo Ngọc",
    userKey: "0253240012",
    parentId: 10059701,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
];
final List<PhoneBook> mockPhoneBookStudent = [
  PhoneBook(
    pupilId: 10056998,
    userId: 10126038,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Lê Thanh Phong",
    userKey: "0253240031",
    parentId: 10059823,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    phoneNumber: '0987 888 888',
    parentName: 'Nguyễn Kiều Cẩm Thơ',
  ),
  PhoneBook(
    pupilId: 10056997,
    userId: 10126036,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Xuân Phúc",
    userKey: "0253240030",
    parentId: 10059822,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    phoneNumber: '0987 888 888',
    parentName: 'Quế Ngọc Hải',
  ),
  PhoneBook(
    pupilId: 10056996,
    userId: 10126034,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Trần Bảo Anh",
    userKey: "0253240029",
    parentId: 10059821,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    phoneNumber: '0987 888 888',
    parentName: 'Trương Ánh Hoa',
  ),
  PhoneBook(
    pupilId: 10056979,
    userId: 10125980,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Vũ Lê Thiên Phúc",
    userKey: "0253240023",
    parentId: 10059804,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056978,
    userId: 10125978,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Bùi Tiến Minh",
    userKey: "0253240022",
    parentId: 10059803,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056977,
    userId: 10125976,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Hoàng Ánh Minh",
    userKey: "0253240021",
    parentId: 10059802,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056973,
    userId: 10125960,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Gia Phúc",
    userKey: "0253240019",
    parentId: 10059798,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056881,
    userId: 10125728,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Bùi Quốc",
    userKey: "0253240014",
    parentId: 10059703,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056880,
    userId: 10125725,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Trần Phương Anh",
    userKey: "0253240013",
    parentId: 10059702,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
  PhoneBook(
    pupilId: 10056879,
    userId: 10125723,
    schoolId: 125,
    schoolName: "UKA Bà Rịa",
    classId: 6021,
    fullName: "Nguyễn Bảo Ngọc",
    userKey: "0253240012",
    parentId: 10059701,
    className: "1.1",
    urlImage: UrlImage(
      web: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
      mobile: "https://test-iportal.nhg.vn/api/images/no_image.jpg",
    ),
    email: "",
    indentifier: "",
    capDaoTao: CapDaoTao(
      id: "C_003",
      name: "Tiểu Học",
    ),
    parentName: 'Trương Ánh Hoa',
    phoneNumber: '0987 888 888',
  ),
];

final List<PhoneBook> phoneBookTeacher = [];
